# Generated by Django 4.0.5 on 2022-07-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_alg', '0001_initial'),
        ('padron', '0018_remove_lotes_establecimiento_remove_lotes_padron_and_more'),
        ('chofer_camion', '0002_chofer_padron'),
        ('lotes', '0002_alter_lotes_numero_lote'),
        ('establecimiento', '0001_initial'),
        ('variedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanza',
            fields=[
                ('numero_remito', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('codigo_productor', models.BigIntegerField(unique=True)),
                ('cuit_chofer', models.IntegerField(verbose_name='cuit_chofer')),
                ('patente_camion', models.CharField(max_length=20, verbose_name='patente_chasis')),
                ('patente_acoplado', models.CharField(max_length=20, verbose_name='patente_acomplado')),
                ('fecha_actual', models.DateField(verbose_name='fecha_actual')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chofer_camion.chofer', verbose_name='codigo_transportista')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento', verbose_name='codigo_establecimiento')),
                ('lotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotes', verbose_name='numero_lote')),
                ('padron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.padron', verbose_name='codigo_cliente')),
                ('tipo_alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_alg.tipo_alg', verbose_name='codigo_cosecha')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedad.variedad', verbose_name='codigo_variedadSemilla')),
            ],
            options={
                'db_table': 'balanza',
            },
        ),
    ]
