# Generated by Django 4.0.5 on 2022-07-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='numero_remito',
            field=models.BigAutoField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
