# Generated by Django 4.0.5 on 2022-07-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0002_alter_balanza_numero_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='numero_remito',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
