# Generated by Django 4.0.5 on 2022-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanza', '0003_alter_balanza_numero_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanza',
            name='numero_remito',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
