# Generated by Django 4.0.5 on 2022-07-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('codigo_transportista', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_transportista', models.CharField(max_length=30)),
                ('carnet_conducir_chofer', models.IntegerField()),
                ('num_cuit_chofer', models.IntegerField()),
            ],
            options={
                'db_table': 'chofer',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_camion', models.CharField(max_length=20)),
                ('patente_acomplado', models.CharField(max_length=20)),
                ('chofer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chofer_camion.chofer')),
            ],
            options={
                'db_table': 'camion',
            },
        ),
    ]
