# Generated by Django 4.0.5 on 2022-06-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('codigo_transportista', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_transportista', models.CharField(max_length=30)),
                ('carnet_conducir_chofer', models.IntegerField()),
                ('num_cuit_chofer', models.IntegerField()),
            ],
            options={
                'db_table': 'chofer',
            },
        ),
    ]
