# Generated by Django 4.0.5 on 2022-06-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chofer_camion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_camion', models.CharField(max_length=20)),
                ('patente_acomplado', models.CharField(max_length=20)),
                ('chofer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chofer_camion.chofer')),
            ],
            options={
                'db_table': 'camion',
            },
        ),
    ]
