# Generated by Django 4.0.5 on 2022-07-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer_camion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='patente_acomplado',
            field=models.CharField(max_length=20, verbose_name='Patente Acoplado'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='patente_camion',
            field=models.CharField(max_length=20, verbose_name='Patente Chasis'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='carnet_conducir_chofer',
            field=models.BigIntegerField(verbose_name='Carnet de Conducir Chofer'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='descripcion_transportista',
            field=models.CharField(max_length=30, verbose_name='Nombre, Apellido, del transportista - Chofer'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='num_cuit_chofer',
            field=models.BigIntegerField(verbose_name='Numero de cuit Chofer'),
        ),
    ]
