# Generated by Django 4.0.5 on 2022-07-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_alg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_alg',
            name='descripcion_cosecha',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('STRIPER', 'STRIPER'), ('USILLO', 'USILLO')], max_length=20),
        ),
    ]
