# Generated by Django 4.0.5 on 2022-07-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_establecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('numero_lote', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.establecimiento')),
                ('padron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.padron')),
            ],
            options={
                'db_table': 'lotes',
            },
        ),
    ]
