# Generated by Django 4.0.5 on 2022-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0004_alter_lotes_numero_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='numero_lote',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
