# Generated by Django 4.0.5 on 2022-07-04 20:58

import apps.padron.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0005_alter_lotes_numero_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='numero_lote',
            field=models.CharField(default=apps.padron.utils.custom_id, max_length=6, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
