# Generated by Django 4.0.5 on 2022-07-04 21:08

import apps.padron.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0008_alter_lotes_numero_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='numero_lote',
            field=models.BigAutoField(default=apps.padron.utils.custom_id, max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
