# Generated by Django 4.0.5 on 2022-07-05 04:25

import apps.padron.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0016_alter_lotes_numero_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='numero_lote',
            field=models.BigIntegerField(default=apps.padron.utils.custom_id, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
