# Generated by Django 4.0.5 on 2022-07-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0017_alter_lotes_numero_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotes',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='lotes',
            name='padron',
        ),
        migrations.AlterField(
            model_name='padron',
            name='codigo_cliente',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Establecimiento',
        ),
        migrations.DeleteModel(
            name='Lotes',
        ),
    ]
